Repository emulsify-ds/emulsify-drupal, pull requests merged in 2019-11, with the labels that each got.

#44 Story format
  .storybook/config.js
  components/00-base/global/01-colors/colors.stories.js
  components/00-base/global/01-colors/colors.twig
  components/00-base/global/animations/animations.stories.js
  components/01-atoms/buttons/buttons.stories.js
  components/01-atoms/forms/forms.stories.js
  components/01-atoms/images/icons/_icons.scss
  components/01-atoms/images/icons/icons.stories.js
  components/01-atoms/images/icons/icons.twig
  components/01-atoms/images/icons/icons.yml
  components/01-atoms/images/image/images.stories.js
  components/01-atoms/images/images.stories.js
  components/01-atoms/links/link/links.stories.js
  components/01-atoms/lists/lists.stories.js
  components/01-atoms/tables/tables.stories.js
  components/01-atoms/text/headings/headings.stories.js
  components/01-atoms/text/text.stories.js
  components/01-atoms/text/text/text.stories.js
  components/01-atoms/video/videos.stories.js
  components/02-molecules/card/cards.stories.js
  components/02-molecules/cta/ctas.stories.js
  components/02-molecules/menus/breadcrumbs/breadcrumbs.stories.js
  components/02-molecules/menus/inline/inline-menu.stories.js
  components/02-molecules/menus/main-menu/main-menu.stories.js
  components/02-molecules/menus/menus.stories.js
  components/02-molecules/menus/social/social-menu.stories.js
  components/02-molecules/menus/tab/tabs.stories.js
  components/02-molecules/menus/tabs/_tab.scss
  components/02-molecules/menus/tabs/_tab.twig
  components/02-molecules/menus/tabs/_tabs.scss
  components/02-molecules/menus/tabs/tabs.js
  components/02-molecules/menus/tabs/tabs.twig
  components/02-molecules/menus/tabs/tabs.yml
  components/02-molecules/pager/pager.stories.js
  components/02-molecules/status/status.stories.js
  components/03-organisms/grid/grids.stories.js
  components/03-organisms/site/site-footer/site-footer.stories.js
  components/03-organisms/site/site-header/site-header.stories.js
  components/03-organisms/site/site.stories.js
  components/04-templates/layouts.stories.js
  components/04-templates/placeholder/place-holder.stories.js
  components/05-pages/content-types/content-types.stories.js
  components/05-pages/landing-pages/landing-pages.stories.js
Labels: Status: Passes code review, Status: Passes functional review

#45 Fix JS methodology
  .eslintrc.yml
  .storybook/_drupal.js
  .storybook/config.js
  babel.config.js
  components/01-atoms/buttons/buttons.stories.js
  components/01-atoms/buttons/twig/button.js
  components/02-molecules/cta/cta.js
  components/02-molecules/menus/main-menu/main-menu.js
  components/02-molecules/menus/menus.stories.js
  components/02-molecules/menus/tabs/tabs.js
  components/02-molecules/tabs/_tab.scss
  components/02-molecules/tabs/_tab.twig
  components/02-molecules/tabs/_tabs.scss
  components/02-molecules/tabs/tabs.js
  components/02-molecules/tabs/tabs.stories.js
  components/02-molecules/tabs/tabs.twig
  components/02-molecules/tabs/tabs.yml
  components/03-organisms/site/site.stories.js
  components/05-pages/content-types/content-types.stories.js
  components/05-pages/landing-pages/landing-pages.stories.js
  package.json
  webpack/.browserslistrc
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#7 Composer install
  .gitignore
  LICENSE
  composer.json
Labels: Status: Feedback Needed, Status: Passes code review

#47 Drupal fixes
  .editorconfig
  .storybook/config.js
  components/01-atoms/images/icons/_icon.twig
  components/01-atoms/images/icons/svgxuse.min.js
  components/01-atoms/tables/tables.twig
  components/01-atoms/text/text/03-inline-elements.twig
  components/01-atoms/text/text/05-pre.twig
  components/02-molecules/tabs/_tab.twig
  components/03-organisms/site/site-header/site-header.twig
  components/03-organisms/site/site-header/site-header.yml
  components/03-organisms/site/site.stories.js
  composer.json
  emulsify.info.yml
  emulsify.libraries.yml
  emulsify.php
  package.json
  templates/block/block--mainnavigation.html.twig
  templates/content/node--article--teaser.html.twig
  templates/content/node.html.twig
  templates/content/page-title.html.twig
  templates/fields/field--text-long.html.twig
  templates/fields/field--text-with-summary.html.twig
  templates/form/checkboxes.html.twig
  templates/form/field-multiple-value-form.html.twig
  templates/form/fieldset.html.twig
  templates/form/form-element-label.html.twig
  templates/form/form-element.html.twig
  templates/form/input.html.twig
  templates/form/radios.html.twig
  templates/form/select.html.twig
  templates/form/textarea.html.twig
  templates/layout/region--header.html.twig
  templates/media/responsive-image.html.twig
  templates/navigation/menu-local-action.html.twig
  templates/navigation/menu-local-task.html.twig
  templates/navigation/menu-local-tasks.html.twig
  templates/views/views-view-unformatted--frontpage.html.twig
  webpack/.stylelintrc
  webpack/loaders.js
  webpack/plugins.js
  webpack/webpack.common.js
  webpack/webpack.prod.js
Labels: Status: Review Needed

#49 ESLint during development
  .eslintignore
  .storybook/webpack.config.js
  components/03-organisms/site/site.stories.js
  components/04-templates/layouts.stories.js
  package.json
Labels: Status: Review Needed
