Repository emulsify-ds/emulsify-drupal, pull requests merged in 2019-10, with the labels that each got.

#9 Twig namespacing
  .storybook/config.js
  .storybook/webpack.config.js
  components/02-molecules/cta/cta.twig
  package.json
Labels: Priority: Critical, Status: Review Needed

#11 Styling Support, base level components
  components/00-base/base.stories.js
  components/00-base/global/01-colors/_color-vars.css
  components/00-base/global/01-colors/_colors-used.css
  components/00-base/global/01-colors/colors.twig
  components/00-base/global/animations/_animation.css
  components/00-base/global/animations/animations.twig
  components/00-base/global/base/_01-variables.css
  components/00-base/global/base/_02-breakpoints.css
  components/00-base/global/base/_03-mixins.css
  components/00-base/global/base/_04-base.css
  components/00-base/layouts/_default.css
  components/00-base/layouts/grid/_01-grid-item.css
  components/00-base/layouts/grid/_grid.css
  components/00-base/layouts/grid/grid.twig
  components/01-atoms/01-links/link/_link.css
  components/01-atoms/01-links/link/link.twig
  components/01-atoms/02-text/00-headings/_heading.twig
  components/01-atoms/02-text/00-headings/_headings.css
  components/01-atoms/02-text/00-headings/headings.twig
  components/01-atoms/02-text/text/01-paragraph.twig
  components/01-atoms/02-text/text/02-blockquote.twig
  components/01-atoms/02-text/text/03-inline-elements.twig
  components/01-atoms/02-text/text/05-preformatted-text.twig
  components/01-atoms/02-text/text/06-hr.twig
  components/01-atoms/02-text/text/_text.scss
  components/01-atoms/06-buttons/Code.mdx
  components/01-atoms/06-buttons/Style.md
  components/01-atoms/06-buttons/Usage.md
  components/01-atoms/06-buttons/buttons.css
  components/01-atoms/06-buttons/react/Button.component.js
  components/01-atoms/06-buttons/twig/button.js
  components/01-atoms/06-buttons/twig/button.twig
  components/01-atoms/atoms.stories.js
  components/01-atoms/button-react/Button.css
  components/01-atoms/button/button.yml
  components/01-atoms/button/buttons.css
  components/02-molecules/cta/cta.twig
  components/02-molecules/cta/cta.yml
  components/style.css
  package.json
  webpack/.stylelintrc
  webpack/postcss.config.js
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#12 Text, Twig cache clear
  .storybook/config.js
  components/01-atoms/02-text/text/03-inline-elements.twig
  components/01-atoms/02-text/text/05-pre.twig
  components/01-atoms/02-text/text/_text.css
  components/01-atoms/atoms.stories.js
Labels: Status: Passes code review, Status: Passes functional review, Status: Review Needed, Status: Shipit

#10 1) Image Minification and SVG spriting
  app.js
  components/01-atoms/atoms.stories.js
  components/01-atoms/images/icons/_icon.twig
  components/01-atoms/images/icons/icons.md
  components/01-atoms/images/icons/icons.twig
  components/01-atoms/images/icons/icons.yml
  images/icons/menu.svg
  images/icons/twitter.svg
  package.json
  webpack/loaders.js
  webpack/plugins.js
  webpack/webpack.config.js
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#13 2) Cleanup
  .github/PULL_REQUEST_TEMPLATE.md
  components/01-atoms/01-links/link/links.stories.js
  components/01-atoms/02-text/00-headings/headings.stories.js
  components/01-atoms/02-text/text/text.stories.js
  components/01-atoms/atoms.stories.js
  components/01-atoms/buttons/Code.mdx
  components/01-atoms/buttons/Style.md
  components/01-atoms/buttons/Usage.md
  components/01-atoms/buttons/buttons.css
  components/01-atoms/buttons/buttons.stories.js
  components/01-atoms/buttons/react/Button.component.js
  components/01-atoms/buttons/twig/button.js
  components/01-atoms/buttons/twig/button.twig
  components/02-molecules/cta/cta.twig
  components/02-molecules/cta/ctas.stories.js
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#15 4) Images
  components/01-atoms/images/icons/icons.stories.js
  components/01-atoms/images/image/_image.twig
  components/01-atoms/images/image/_picture.twig
  components/01-atoms/images/image/figure.twig
  components/01-atoms/images/image/image.css
  components/01-atoms/images/image/images.stories.js
  components/01-atoms/images/image/responsive-image.twig
  src/components/01-atoms/04-images/00-image/00-responsive-image.yml
  src/components/01-atoms/04-images/00-image/02-figure.yml
  src/components/01-atoms/04-images/00-image/_image.twig
  src/components/01-atoms/04-images/00-image/figure.md
  src/components/01-atoms/04-images/00-image/figure.twig
  src/components/01-atoms/04-images/00-image/image~logo.yml
  src/components/01-atoms/04-images/00-image/responsive-image.md
  src/components/01-atoms/04-images/00-image/responsive-image.twig
  src/components/01-atoms/04-images/favicon.twig
  src/components/01-atoms/04-images/icons/_icon.twig
  src/components/01-atoms/04-images/icons/icons.md
  src/components/01-atoms/04-images/icons/icons.twig
  src/components/01-atoms/04-images/icons/icons.yml
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#17 Adds Tables
  components/01-atoms/tables/_tables.css
  components/01-atoms/tables/tables.stories.js
  components/01-atoms/tables/tables.twig
Labels: Status: Review Needed

#20 Initial list components.
  components/01-atoms/lists/_list-item-definition.twig
  components/01-atoms/lists/_list-item.twig
  components/01-atoms/lists/dl.twig
  components/01-atoms/lists/lists.css
  components/01-atoms/lists/lists.stories.js
  components/01-atoms/lists/ol.twig
  components/01-atoms/lists/ul.twig
  src/components/01-atoms/03-lists/00-ul.yml
  src/components/01-atoms/03-lists/01-ol.twig
  src/components/01-atoms/03-lists/01-ol.yml
  src/components/01-atoms/03-lists/02-dl.twig
  src/components/01-atoms/03-lists/02-dl.yml
  src/components/01-atoms/03-lists/_list-item-definition.twig
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#21 Menu - Tabs
  components/01-atoms/lists/lists.stories.js
  components/02-molecules/menus/tab/_tab.twig
  components/02-molecules/menus/tab/tab.css
  components/02-molecules/menus/tab/tabs.css
  components/02-molecules/menus/tab/tabs.js
  components/02-molecules/menus/tab/tabs.stories.js
  components/02-molecules/menus/tab/tabs.twig
  src/components/01-atoms/09-menu/tab/tab.yml
  src/components/02-molecules/menus/tabs/tabs.md
Labels: Status: Review Needed

#24 Menu - Breadcrumb
  components/00-base/global/base/_04-base.css
  components/02-molecules/menus/breadcrumbs/breadcrumbs.css
  components/02-molecules/menus/breadcrumbs/breadcrumbs.stories.js
  components/02-molecules/menus/breadcrumbs/breadcrumbs.twig
  src/components/02-molecules/menus/breadcrumbs/breadcrumbs.twig
  src/components/02-molecules/menus/breadcrumbs/breadcrumbs.yml
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#22 Card
  components/02-molecules/card/card.css
  components/02-molecules/card/card.twig
  components/02-molecules/card/cards.stories.js
  src/components/02-molecules/card/01-card.twig
  src/components/02-molecules/card/_card.scss
  src/components/02-molecules/card/card-bg.md
  src/components/02-molecules/card/card.md
  src/components/02-molecules/card/card.yml
  src/components/02-molecules/card/card~bg.yml
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#26 Status
  components/02-molecules/status/status.css
  components/02-molecules/status/status.stories.js
  components/02-molecules/status/status.twig
  src/components/02-molecules/status/_status.scss
  src/components/02-molecules/status/status.yml
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#29 Placeholder
  .storybook/webpack.config.js
  components/03-organisms/.gitkeep
  components/04-templates/placeholder/place-holder.css
  components/04-templates/placeholder/place-holder.stories.js
  components/04-templates/placeholder/place-holder.twig
  components/style.css
  src/components/04-templates/_place-holder.scss
  src/components/04-templates/_place-holder.twig
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#28 Card grid
  components/00-base/global/base/_01-variables.css
  components/00-base/layouts/grid/_01-grid-item.css
  components/00-base/layouts/grid/grids.stories.js
  components/02-molecules/card/card.twig
  components/02-molecules/cta/cta.twig
  components/03-organisms/.gitkeep
  components/03-organisms/grid/_grid-examples.twig
  components/03-organisms/grid/_grid-item.css
  components/03-organisms/grid/_grid.css
  components/03-organisms/grid/grid.twig
  components/03-organisms/grid/grids.stories.js
  package.json
  webpack/.stylelintrc
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#31 Initial footer component and stories.
  components/02-molecules/menus/social/social-menu.css
  components/02-molecules/menus/social/social-menu.stories.js
  components/02-molecules/menus/social/social-menu.twig
  components/03-organisms/site/site-footer/site-footer.css
  components/03-organisms/site/site-footer/site-footer.stories.js
  components/03-organisms/site/site-footer/site-footer.twig
  components/04-templates/_default.css
  images/icons/facebook.svg
  images/icons/instagram.svg
  src/components/03-organisms/site/site-footer/_site-footer.scss
  src/components/03-organisms/site/site-footer/site-footer.twig
  src/components/03-organisms/site/site-footer/site-footer.yml
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#27 Handling Component JS for Storybook/Drupal
  .gitignore
  .storybook/config.js
  README.md
  app.js
  components/01-atoms/buttons/buttons.stories.js
  components/01-atoms/buttons/twig/button.js
  package.json
  webpack/.browserslistrc
  webpack/.eslintignore
  webpack/.eslintrc.yml
  webpack/app.js
  webpack/babel.config.js
  webpack/css.js
  webpack/loaders.js
  webpack/plugins.js
  webpack/svgSprite.js
  webpack/webpack.common.js
  webpack/webpack.config.js
  webpack/webpack.dev.js
  webpack/webpack.prod.js
Labels: Status: Passes functional review, Status: Review Needed

#30 Header
  components/01-atoms/images/icons/_icon.twig
  components/03-organisms/site/site-header/site-header.css
  components/03-organisms/site/site-header/site-header.stories.js
  components/03-organisms/site/site-header/site-header.twig
  images/logo.png
  package.json
  src/components/03-organisms/site/site-header/_site-header.scss
  src/components/03-organisms/site/site-header/site-header.twig
  src/components/03-organisms/site/site-header/site-header.yml
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#32 Templates
  components/03-organisms/site/site-footer/site-footer.twig
  components/04-templates/_default.twig
  components/04-templates/full-width.twig
  components/04-templates/layouts.stories.js
  components/04-templates/with-sidebar.twig
  src/components/04-templates/full-width.twig
Labels: Status: Review Needed

#35 ESLint
  .eslintrc.yml
  README.md
  components/00-base/global/01-colors/colors.stories.js
  components/00-base/global/animations/animations.stories.js
  components/01-atoms/buttons/buttons.stories.js
  components/01-atoms/buttons/react/Button.component.js
  components/01-atoms/buttons/twig/button.js
  components/01-atoms/forms/forms.stories.js
  components/01-atoms/images/icons/icons.stories.js
  components/01-atoms/images/image/images.stories.js
  components/01-atoms/links/link/links.stories.js
  components/01-atoms/lists/lists.stories.js
  components/01-atoms/tables/tables.stories.js
  components/01-atoms/text/headings/headings.stories.js
  components/01-atoms/text/text/text.stories.js
  components/01-atoms/video/videos.stories.js
  components/02-molecules/card/cards.stories.js
  components/02-molecules/cta/cta.js
  components/02-molecules/cta/ctas.stories.js
  components/02-molecules/menus/breadcrumbs/breadcrumbs.stories.js
  components/02-molecules/menus/inline/inline-menu.stories.js
  components/02-molecules/menus/social/social-menu.stories.js
  components/02-molecules/menus/tab/tabs.js
  components/02-molecules/menus/tab/tabs.stories.js
  components/02-molecules/pager/pager.stories.js
  components/02-molecules/status/status.stories.js
  components/03-organisms/grid/grids.stories.js
  components/03-organisms/site/site-footer/site-footer.stories.js
  components/03-organisms/site/site-header/site-header.stories.js
  components/04-templates/layouts.stories.js
  components/04-templates/placeholder/place-holder.stories.js
  package.json
  webpack/.eslintignore
  webpack/.eslintrc.yml
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#36 Accessibility Testing in Storybook
  .storybook/addons.js
  .storybook/config.js
  components/00-base/global/01-colors/_color-vars.css
  components/01-atoms/buttons/twig/button.twig
  components/01-atoms/forms/checkbox/checkbox.twig
  components/01-atoms/forms/radio/radio.twig
  components/01-atoms/forms/select/select.twig
  components/01-atoms/forms/textfields/textfields.twig
  components/01-atoms/video/videos.stories.js
  components/02-molecules/menus/breadcrumbs/breadcrumbs.css
  components/02-molecules/menus/breadcrumbs/breadcrumbs.twig
  components/02-molecules/pager/pager.css
  components/02-molecules/pager/pager.stories.js
  components/02-molecules/pager/pager.twig
  components/02-molecules/status/status.twig
  components/03-organisms/grid/_grid-examples.twig
  components/03-organisms/grid/grids.stories.js
  package.json
Labels: Status: Passes functional review

#33 Pages
  .storybook/globalData.js
  components/01-atoms/video/videos.stories.js
  components/03-organisms/grid/grid.twig
  components/03-organisms/grid/grids.stories.js
  components/03-organisms/site/site-header/site-header.css
  components/03-organisms/site/site-header/site-header.stories.js
  components/03-organisms/site/site-header/site-header.twig
  components/04-templates/_default.css
  components/04-templates/full-width.twig
  components/04-templates/layouts.stories.js
  components/04-templates/with-sidebar.twig
  components/05-pages/content-types/article.twig
  components/05-pages/content-types/content-types.stories.js
  components/05-pages/landing-pages/home.twig
  components/05-pages/landing-pages/landing-pages.stories.js
  src/components/05-pages/article/article.twig
  src/components/05-pages/home/home.twig
Labels: Status: Review Needed

#38 Main menu
  .storybook/globalData.js
  components/02-molecules/menus/main-menu/00-main-menu.css
  components/02-molecules/menus/main-menu/01-main-menu-item.css
  components/02-molecules/menus/main-menu/02-main-menu-link.css
  components/02-molecules/menus/main-menu/03-main-menu-toggle.css
  components/02-molecules/menus/main-menu/main-menu.js
  components/02-molecules/menus/main-menu/main-menu.stories.js
  components/02-molecules/menus/main-menu/main-menu.twig
  components/03-organisms/site/site-header/site-header.css
  components/03-organisms/site/site-header/site-header.stories.js
  components/03-organisms/site/site-header/site-header.twig
  components/04-templates/_default.twig
  components/04-templates/layouts.stories.js
  components/05-pages/content-types/article.twig
  components/05-pages/content-types/content-types.stories.js
  components/05-pages/landing-pages/home.twig
  components/05-pages/landing-pages/landing-pages.stories.js
  src/components/02-molecules/menus/main-menu/main-menu.js
  src/components/02-molecules/menus/main-menu/main-menu.md
  src/components/02-molecules/menus/main-menu/main-menu.yml
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#39 Custom Storybook theme
  .storybook/config.js
  .storybook/emulsifyTheme.js
  components/00-base/global/01-colors/_color-vars.css
Labels: Status: Passes code review, Status: Passes functional review
