Repository emulsify-ds/emulsify-drupal, pull requests merged in 2020-09, with the labels that each got.

#121 Modernize :placeholder CSS
  components/01-atoms/forms/textfields/_textfields.scss
Labels: Priority: Low, Status: Review Needed

#126 Emulsify twig update
  composer.json
  package.json
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#128 build: add husky and lint-staged, and configure prettier
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierignore
  .storybook/_drupal.js
  .storybook/config.js
  CODE_OF_CONDUCT.md
  README.md
  components/00-base/01-colors/_00-colors-vars.scss
  components/00-base/02-motion/_motion.scss
  components/01-atoms/buttons/twig/button.yml
  emulsify.info.yml
  emulsify.libraries.yml
  husky.config.js
  lint-staged.config.js
  package.json
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#108 GS-144: Drupal 9 & Automated Semantic Release
  .github/workflows/dev-sync.yml
  .github/workflows/semantic-release.yml
  .releaserc.js
  README.md
  emulsify.info.yml
  emulsify.php
  package.json
Labels: Status: Passes code review, Status: Passes functional review

#127 test(gs-141): set up testing approach and tools
  .eslintrc.yml
  .storybook/config.js
  .storybook/setupTwig.js
  .storybook/setupTwig.test.js
  .storybook/webpack.config.js
  babel.config.js
  components/01-atoms/buttons/react/Button.test.js
  components/01-atoms/buttons/twig/button.twig.test.js
  components/01-atoms/forms/checkbox/checkbox.twig.test.js
  components/01-atoms/forms/radio/radio.twig.test.js
  components/01-atoms/forms/select/select.twig.test.js
  components/01-atoms/forms/textfields/__snapshots__/textfields.twig.test.js.snap
  components/01-atoms/forms/textfields/textfields.twig.test.js
  components/01-atoms/images/icons/__snapshots__/icons.twig.test.js.snap
  components/01-atoms/images/icons/icons.twig.test.js
  components/01-atoms/images/image/figure.twig.test.js
  components/01-atoms/links/link/link.twig.test.js
  components/01-atoms/lists/__snapshots__/lists.twig.test.js.snap
  components/01-atoms/lists/lists.twig.test.js
  components/01-atoms/tables/__snapshots__/tables.twig.test.js.snap
  components/01-atoms/tables/tables.twig.test.js
  components/01-atoms/text/headings/heading.twig.test.js
  components/01-atoms/text/text/__snapshots__/text.twig.test.js.snap
  components/01-atoms/text/text/text.twig.test.js
  components/01-atoms/video/video.twig.test.js
  components/02-molecules/card/__snapshots__/card.twig.test.js.snap
  components/02-molecules/card/card.twig.test.js
  components/02-molecules/cta/cta.twig.test.js
  components/02-molecules/menus/breadcrumbs/breadcrumbs.twig.test.js
  components/02-molecules/menus/inline/inline-menu.twig.test.js
  components/02-molecules/menus/main-menu/__snapshots__/main-menu.twig.test.js.snap
  components/02-molecules/menus/main-menu/main-menu.twig.test.js
  components/02-molecules/menus/social/__snapshots__/social.twig.test.js.snap
  components/02-molecules/menus/social/social.twig.test.js
  components/02-molecules/pager/__snapshots__/pager.twig.test.js.snap
  components/02-molecules/pager/pager.twig.test.js
  components/02-molecules/status/status.twig.test.js
  components/02-molecules/tabs/__snapshots__/tabs.yml.test.js.snap
  components/02-molecules/tabs/tabs.yml.test.js
  jest.config.js
  package.json
  util/loadYaml.js
  util/loadYaml.test.js
Labels: Status: Passes code review, Status: Passes functional review

#137 test(gs-141): add tests for all remaining components
  components/03-organisms/grid/__snapshots__/grid.twig.test.js.snap
  components/03-organisms/grid/grid.twig.test.js
  components/03-organisms/site/site-footer/site-footer.twig.test.js
  components/03-organisms/site/site-header/site-header.twig.test.js
  components/04-templates/__snapshots__/full-width.twig.test.js.snap
  components/04-templates/__snapshots__/with-sidebar.twig.test.js.snap
  components/04-templates/full-width.twig.test.js
  components/04-templates/placeholder/placeholder.twig.test.js
  components/04-templates/with-sidebar.twig.test.js
  components/05-pages/content-types/__snapshots__/article.twig.test.js.snap
  components/05-pages/content-types/article.twig.test.js
  components/05-pages/landing-pages/__snapshots__/home.twig.test.js.snap
  components/05-pages/landing-pages/home.twig.test.js
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#136 GH-117: Babel/Core-JS@3 and IE11 Custom properties fixes, source map support
  .storybook/webpack.config.js
  components/02-molecules/menus/main-menu/main-menu.js
  package.json
  postcss.config.js
  webpack/loaders.js
  webpack/plugins.js
  webpack/postcss.config.js
  webpack/webpack.common.js
  webpack/webpack.dev.js
  webpack/webpack.prod.js
Labels: Priority: Critical, Status: Passes code review, Status: Passes functional review

#134 Storybook 6 Upgrade
  .storybook/addons.js
  .storybook/config.js
  .storybook/main.js
  .storybook/preview.js
  components/05-pages/landing-pages/landing-pages.stories.js
  package.json
Labels: Priority: Medium, Status: Passes code review, Status: Passes functional review

#139 GH-118: Footer file
  templates/layout/region--footer.html.twig
Labels: Priority: Low, Status: Review Needed

#144 Fix: Drupal Components module Drupal 9 requirement, jest ignore vendor directory
  composer.json
  jest.config.js
Labels: Status: Review Needed
