Repository emulsify-ds/emulsify-drupal, pull requests merged in 2020-02, with the labels that each got.

#58 Docs
  components/01-atoms/images/icons/_icon.twig
  components/03-organisms/site/site-header/site-header.twig
  components/03-organisms/site/site-header/site-header.yml
  components/03-organisms/site/site.stories.js
Labels: Status: Passes code review

#56 PHP script none argument
  emulsify.php
Labels: Priority: Low, Status: Review Needed, Type: Feature

#59 Add prettier to EDS
  .eslintrc.yml
  .storybook/_drupal.js
  .storybook/config.js
  .storybook/emulsifyTheme.js
  .storybook/webpack.config.js
  babel.config.js
  components/00-base/01-colors/colors.stories.js
  components/00-base/animations/_animation.scss
  components/00-base/animations/animations.stories.js
  components/00-base/base/_01-variables.scss
  components/00-base/base/_03-mixins.scss
  components/01-atoms/buttons/_buttons.scss
  components/01-atoms/buttons/buttons.stories.js
  components/01-atoms/buttons/react/Button.component.js
  components/01-atoms/forms/forms.stories.js
  components/01-atoms/forms/select/_select.scss
  components/01-atoms/images/images.stories.js
  components/01-atoms/links/link/links.stories.js
  components/01-atoms/lists/lists.stories.js
  components/01-atoms/tables/tables.stories.js
  components/01-atoms/text/headings/_headings.scss
  components/01-atoms/text/text.stories.js
  components/01-atoms/video/videos.stories.js
  components/02-molecules/card/cards.stories.js
  components/02-molecules/cta/ctas.stories.js
  components/02-molecules/menus/breadcrumbs/_breadcrumbs.scss
  components/02-molecules/menus/main-menu/_01-main-menu-item.scss
  components/02-molecules/menus/main-menu/_02-main-menu-link.scss
  components/02-molecules/menus/main-menu/_03-main-menu-toggle.scss
  components/02-molecules/menus/main-menu/main-menu.js
  components/02-molecules/menus/menus.stories.js
  components/02-molecules/pager/_pager.scss
  components/02-molecules/pager/pager.stories.js
  components/02-molecules/status/status.stories.js
  components/02-molecules/tabs/tabs.js
  components/03-organisms/grid/grids.stories.js
  components/03-organisms/site/site.stories.js
  components/04-templates/layouts.stories.js
  components/04-templates/placeholder/place-holder.stories.js
  components/05-pages/landing-pages/landing-pages.stories.js
  components/style.scss
  gatsby-config.js
  package.json
  prettier.config.js
  webpack/.stylelintrc
Labels: Status: Passes code review, Status: Passes functional review, Type: Enhancement

#64 Remove Pattern Lab references and also change to component library lingo
  components/02-molecules/tabs/tabs.twig
  components/03-organisms/grid/_grid-item.scss
  composer.json
  emulsify.info.yml
  emulsify.theme
  package.json
  styleguide/0__Getting started/0__Welcome.mdx
  styleguide/1__Documentation/1__Storybook.md
Labels: Priority: Medium, Status: Passes code review, Status: Shipit
