Repository emulsify-ds/emulsify-drupal, pull requests merged in 2020-05, with the labels that each got.

#92 GH-87: Fix div element
  components/03-organisms/site/site-footer/site-footer.twig
Labels: Priority: Critical, Status: Passes code review, Status: Shipit

#76 Twig Drupal Filters 'without' filter update changes
  components/02-molecules/pager/pager-both-ellipses.yml
  components/02-molecules/pager/pager-ellipses.yml
  components/02-molecules/pager/pager-prev-ellipses.yml
  components/02-molecules/pager/pager.yml
  components/02-molecules/status/status.yml
  package.json
Labels: Priority: Medium, Status: Passes code review, Status: Passes functional review, Status: Shipit

#82 GH-46: Fix menu links to show attributes using link
  components/02-molecules/menus/_menu-item.twig
  components/02-molecules/menus/_menu.twig
  components/02-molecules/menus/main-menu/_02-main-menu-link.scss
Labels: Priority: Medium, Status: Passes code review, Status: Passes functional review, Status: Shipit

#84 reviewed color work, refined animations examples
  components/00-base/01-colors/_00-colors-vars.scss
  components/00-base/01-colors/_01-colors-used.scss
  components/00-base/01-colors/colors.stories.js
  components/00-base/02-animations/_animation.scss
  components/00-base/02-animations/animations.stories.js
  components/00-base/02-animations/animations.twig
  components/00-base/02-motion/_motion.scss
  components/00-base/02-motion/motion.stories.js
  components/00-base/02-motion/motion.twig
  components/00-base/02-motion/motion.yml
  components/01-atoms/images/icons/_icons.scss
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#99 .nvmrc
  .nvmrc
Labels: Status: Passes code review, Status: Passes functional review, Status: Shipit

#98 Updated the icons.md docs.
  components/01-atoms/images/icons/icons.md
Labels: Status: Passes code review, Status: Shipit
