Repository emulsify-ds/emulsify-drupal, pull requests merged in 2021-01, with the labels that each got.

#176 fix: jest should ignore the .out directory when looking for tests
  jest.config.js
Labels: Status: Passes code review, Status: Passes functional review

#178 fix(.nvmrc): fix error in nvmrc version
  .nvmrc
Labels: Status: Passes code review, Status: Passes functional review

#182 Bug: upgrade storybook/react, upgrade/move react, fix build storybook command
  package.json
Labels: Priority: Medium, Status: Passes code review, Status: Passes functional review, Type: Bug

#183 upgrade storybook/react, upgrade/move react, fix build storybook command
  package.json
Labels: Status: Review Needed

#185 Feat/react release
  package.json
Labels: Status: Passes code review
